mrs:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    # Khz
    publish_rate: 10

# The joints
  1_L1_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: 1_L1_j1
    pid: {p: 70.0, i: 0.0, d: 3.0}
  1_L1_j2_position_controller:
    type: effort_controllers/JointPositionController
    joint: 1_L1_j2
    pid: {p: 100.0, i: 0.0, d: 1.0}
  1_L1_j3_position_controller:
    type: effort_controllers/JointPositionController
    joint: 1_L1_j3
    pid: {p: 30.0, i: 0.0, d: 1.2}
  2_L1_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: 2_L1_j1
    pid: {p: 10.0, i: 0.0, d: 0.0}
  2_L1_j2_position_controller:
    type: effort_controllers/JointPositionController
    joint: 2_L1_j2
    pid: {p: 10.0, i: 0.0, d: 0.0}
  2_L1_j3_position_controller:
    type: effort_controllers/JointPositionController
    joint: 2_L1_j3
    pid: {p: 10.0, i: 0.0, d: 0.0}   
  1_W1_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: 1_W1_j1
    pid: {p: 10.0, i: 0.0, d: 0.0}
  1_W1_j2_position_controller:
    type: effort_controllers/JointPositionController
    joint: 1_W1_j2
    pid: {p: 10.0, i: 0.0, d: 0.0}
  1_W1_j3_position_controller:
    type: effort_controllers/JointPositionController
    joint: 1_W1_j3
    pid: {p: 10.0, i: 0.0, d: 0.0}
  2_W1_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: 2_W1_j1
    pid: {p: 10.0, i: 0.0, d: 0.0}
  2_W1_j2_position_controller:
    type: effort_controllers/JointPositionController
    joint: 2_W1_j2
    pid: {p: 10.0, i: 0.0, d: 0.0}
  2_W1_j3_position_controller:
    type: effort_controllers/JointPositionController
    joint: 2_W1_j3
    pid: {p: 10.0, i: 0.0, d: 0.0}
