<?xml version="1.0"?>
<robot name="mrs" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Import Rviz colors -->
  <xacro:include filename="$(find mrs_description)/urdf/materials.urdf.xacro" />

  <xacro:property name="JMlen" value=".1" />
  <xacro:property name="JMwidth" value=".4" />
  <xacro:property name="JMheight" value=".3" />


  <xacro:macro name="joint_module_diff_drive" params="parent prefix instance scale rotate">

<!-- Mobile robot using 1 JM - joint 2 should be made fixed -->
    <xacro:jm_sphere_link parent="${parent}" prefix="${prefix}" instance="0" scale="${scale}" type="fixed"/>
    <xacro:jm_rec_link parent="${prefix}_jm_link2_0" prefix="${prefix}" instance="1" scale="${scale}" rotate="0" reflect="-1" translateX="0" translateY="0"/>
    <xacro:jm_rec_link parent="${prefix}_jm_link2_0" prefix="${prefix}" instance="2" scale="${scale}" rotate="0" reflect="1" translateX="0" translateY="0"/>
    
    <xacro:simple_transmission joint="${prefix}_jm_joint_1" />
    <xacro:simple_transmission joint="${prefix}_jm_joint_2" />
    <xacro:diff_drive ljoint="${prefix}_jm_joint_1" rjoint="${prefix}_jm_joint_2" parent="${parent}"  />

  </xacro:macro>
  
    <xacro:macro name="joint_module_3DOF_vertical" params="parent prefix instance scale rotate">
<!-- Mobile robot with 2 or More JM  -->
    <xacro:jm_rec_link parent="${parent}" prefix="${prefix}" instance="1" scale="${scale}" rotate="${rotate}" reflect="0" translateX="0" translateY="0.1"/>
    <xacro:jm_sphere_link parent="${prefix}_jm_link_${instance}" prefix="${prefix}" instance="${instance}" scale="${scale}" type="revolute"/>
    <xacro:jm_rec_link parent="${prefix}_jm_link2_${instance}" prefix="${prefix}" instance="2" scale="${scale}" rotate="0" reflect="1" translateX="0" translateY="0"/>
    
    <xacro:simple_transmission joint="${prefix}_jm_joint_1" />
    <xacro:simple_transmission joint="${prefix}_jm_joint_2" />
    <xacro:simple_transmission joint="${prefix}_jm_joint2_1" />
<!--
Manipulator - rotate =1 
-->
<!--
    <xacro:jm_rec_link parent="${parent}" prefix="${prefix}" instance="${instance-1}" scale="${scale}" rotate="1"/>
    <xacro:jm_sphere_link parent="${prefix}_jm_link_${instance-1}" prefix="${prefix}" instance="${instance}" scale="${scale}" type="revolute" />
    <xacro:jm_rec_link parent="${prefix}_jm_link2_${instance}" prefix="${prefix}" instance="${instance}" scale="${scale}" rotate="0" />
-->

  </xacro:macro>
  <xacro:macro name="joint_module_3DOF" params="parent prefix instance scale rotate">
<!-- Mobile robot with 2 or More JM  -->
    <xacro:jm_rec_link parent="${parent}" prefix="${prefix}" instance="1" scale="${scale}" rotate="${rotate}" reflect="1" translateX="0" translateY="0"/>
    <xacro:jm_sphere_link parent="${prefix}_jm_link_${instance}" prefix="${prefix}" instance="${instance}" scale="${scale}" type="revolute"/>
    <xacro:jm_rec_link parent="${prefix}_jm_link2_${instance}" prefix="${prefix}" instance="2" scale="${scale}" rotate="0" reflect="1" translateX="0" translateY="0"/>
    
    <xacro:simple_transmission joint="${prefix}_jm_joint_1" />
    <xacro:simple_transmission joint="${prefix}_jm_joint_2" />
    <xacro:simple_transmission joint="${prefix}_jm_joint2_1" />
<!--
Manipulator - rotate =1 
-->
<!--
    <xacro:jm_rec_link parent="${parent}" prefix="${prefix}" instance="${instance-1}" scale="${scale}" rotate="1"/>
    <xacro:jm_sphere_link parent="${prefix}_jm_link_${instance-1}" prefix="${prefix}" instance="${instance}" scale="${scale}" type="revolute" />
    <xacro:jm_rec_link parent="${prefix}_jm_link2_${instance}" prefix="${prefix}" instance="${instance}" scale="${scale}" rotate="0" />
-->

  </xacro:macro>
  
  
  
  <xacro:macro name="jm_rec_link" params="parent prefix instance scale rotate reflect translateX translateY">
    <link name="${prefix}_jm_link_${instance}">
      <visual>
        <geometry>
          <box size="${JMlen*scale} ${JMwidth*scale} ${JMheight*scale}" />
        </geometry>
        <material name="Grey2">
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${JMlen*scale} ${JMwidth*scale} ${JMheight*scale}" />
        </geometry>
      </collision>
      <xacro:default_inertial mass="1" I_tensor="1"/>
    </link>
    <joint name="${prefix}_jm_joint_${instance}" type="continuous">
      <parent link="${parent}" />
      <child link="${prefix}_jm_link_${instance}" />
      <axis xyz="1 0 0"/>
      <origin xyz="${(reflect)*(JMlen+JMwidth)/2} ${translateX} ${translateY}" rpy="0 ${-rotate*pi/2} 0" />
    </joint>
      <xacro:gazebo_visual link="${prefix}_jm_link_${instance}" visual="Grey" />
  </xacro:macro>
    
    <xacro:macro name="jm_sphere_link" params="parent prefix instance scale type">
      <link name="${prefix}_jm_link2_${instance}">
        <visual>
          <geometry>
            <sphere radius="${JMwidth/2*scale}"/>
          </geometry>
          <material name="Grey2">
          </material>
        </visual>
        <collision>
          <geometry>
            <sphere radius="${JMwidth/2*scale}"/>
          </geometry>
        </collision>
        <xacro:default_inertial mass="1" I_tensor="1"/>
      </link>
      <joint name="${prefix}_jm_joint2_${instance}" type="${type}">
        <parent link="${parent}" />
        <child link="${prefix}_jm_link2_${instance}" />
        <origin xyz="${instance*(JMlen+JMwidth)/2} 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1"/>
        <limit effort="100" velocity="100" lower="${-pi/2}"
        upper="${pi/2}" />
      </joint>
      <xacro:gazebo_visual link="${prefix}_jm_link2_${instance}" visual="Grey" />
    </xacro:macro>
    
    <xacro:macro name="diff_drive" params="ljoint rjoint parent">
      <!-- CONTROLLERS -->
      <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
          <alwaysOn>true</alwaysOn>
          <updateRate></updateRate>
          <leftJoint>${ljoint}</leftJoint>
          <rightJoint>${rjoint}</rightJoint>
          <wheelSeparation>0.6</wheelSeparation>
          <wheelDiameter>0.6</wheelDiameter>
          <torque>20</torque>
          <commandTopic>mrs/cmd_vel</commandTopic>
          <odometryTopic>odom</odometryTopic>
          <odometryFrame>odom</odometryFrame>
          <robotBaseFrame>${parent}</robotBaseFrame>
        </plugin>
    </gazebo>


    </xacro:macro>
    
    <xacro:macro name="pcm_module" params="parent prefix instance scale len z x rotate">
      <link name="${prefix}_pcm_link_${instance}">
        <visual>
          <geometry>
            <box size="${len*scale} ${len*scale} ${len*scale}" />
          </geometry>
          <material name="Blue">
          </material>
        </visual>
        <collision>
          <geometry>
            <box size="${len*scale} ${len*scale} ${len*scale}" />
          </geometry>
        </collision>
        <xacro:default_inertial mass="0.01" I_tensor="1"/>
      </link>
      <joint name="${prefix}_pcm_joint_${instance}" type="fixed">
        <parent link="${parent}" />
        <child link="${prefix}_pcm_link_${instance}" />
        <origin xyz="${x} 0 ${z}" rpy="0 ${-rotate*pi/2} 0" />
      </joint>
      <xacro:gazebo_visual link="${prefix}_pcm_link_${instance}" visual="Blue" />
    </xacro:macro>
    


  <xacro:macro name="cuboid_inertial" params="mass len height width">
    <inertia ixx="${mass*(len*len+height*height)/12}" ixy="0" ixz="0" iyy="${mass*(width*width+len*len)/12}" iyz="0" izz="${(mass*(width*width+height*height)/12}"/>
  </xacro:macro>

  <xacro:macro name="cylinder_inertial" params="mass len radius">
    <inertia ixx="${mass*(len*len+3*radius*radius)/12}" ixy="0" ixz="0" iyy="${mass*(len*len+3*radius*radius)/12}" iyz="0" izz="${(mass*(radius*radius)/2}"/>
  </xacro:macro>
    
  <xacro:macro name="default_inertial" params="mass I_tensor">
<!--
      Inertia of solid cuboid - m*l*2/6
      Inertia of solid sphere - m*r*r*2/5 
-->
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${I_tensor}" ixy="0.0" ixz="0.0" iyy="${I_tensor}" iyz="0.0" izz="${I_tensor}"/>
    </inertial>
  </xacro:macro>   
 

  <xacro:macro name="sm_wheel" params="parent prefix instance dia length rotate x y">
    <link name="${prefix}_sm_wheel_link_${instance}">
      <visual>
        <geometry>
          <cylinder radius="${dia/2}" length="${length}" />
        </geometry>
          <material name="Black">
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${dia/2}" length="${length}" />
        </geometry>
      </collision>
      <xacro:default_inertial mass="1" I_tensor="1"/>
    </link>

    <joint name="${prefix}_sm_wheel_joint_${instance}" type="fixed">
      <parent link="${parent}" />
      <child link="${prefix}_sm_wheel_link_${instance}" />
      <origin xyz="${x*((JMlen+length)/2)} ${y} 0" rpy=" 0 ${rotate*pi/2} 0" />
    </joint>

    <xacro:gazebo_visual link="${prefix}_sm_wheel_link_${instance}" visual="White" />
  </xacro:macro> 
  
  
  <xacro:macro name="gazebo_visual" params="link visual">
    <gazebo reference = "${link}">
      <material>Gazebo/${visual}</material>
      <selfCollide>false</selfCollide>
    </gazebo>
  </xacro:macro>   
  
    <!-- Transmission's Macro -->
  <macro name="simple_transmission" params="joint">
    <transmission name="${joint}tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint}" />
      <actuator name="${joint}_motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </macro>
</robot>
