<?xml version="1.0"?>
<robot name="mrs" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot -->
  <xacro:include filename="$(find mrs_description)/urdf/common_mrs.xacro" />
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find mrs_description)/urdf/simplified_mrs.xacro" />
  <!-- materials for visualization -->
<!--
  <xacro:include filename="$(find mrs_description)/urdf/materials.urdf.xacro" />
-->
  
  
  <xacro:macro name="initialising_frame" params="name scale prefix">  
  <link name="${name}">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
      <material name="Red"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="${name}_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <child link="${name}_dummy"/>
    <parent link="${name}"/>
  </joint>
  <link name="${name}_dummy"/>

  
  <xacro:pcm_module parent="${name}" prefix="${prefix}" instance="1" scale="${scale}" len="0.35" z="0" x="0.175" rotate="0" />
  <xacro:pcm_module parent="${name}" prefix="${prefix}" instance="2" scale="${scale}" len="0.35" z="0" x="-0.175" rotate="2"/>   

  <xacro:joint_module_3DOF parent="${prefix}_pcm_link_1" prefix="1" instance="1" scale="${scale}" rotate="0"/>
  <xacro:joint_module_3DOF parent="${prefix}_pcm_link_2" prefix="2" instance="1" scale="${scale}" rotate="0"/>
  <xacro:sm_wheel parent="1_jm_link_2" prefix="${prefix}" instance="1" dia="${JMwidth+0.3}" length="0.2" rotate="1" x="1" y="0"/>     
  <xacro:sm_wheel parent="2_jm_link_2" prefix="${prefix}" instance="2" dia="${JMwidth+0.3}" length="0.2" rotate="1" x="1" y="0"/>
  
  <xacro:diff_drive ljoint="2_jm_joint_2" rjoint="1_jm_joint_2" parent="${name}_dummy"  />

  </xacro:macro>   


<!-- For 2 JM 2 PC 2 WM mobile robot -->

  <xacro:initialising_frame name="base_footprint" scale="1" prefix="mrs"/>
  
  <gazebo>

    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/mrs</robotNamespace>
    </plugin>

  </gazebo>

  
</robot>
