<?xml version="1.0"?>
<robot name="mrs" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot -->
  <xacro:include filename="$(find mrs_description)/urdf/common_mrs.xacro" />

  <!-- Import Rviz colors -->
  <xacro:include filename="$(find mrs_description)/urdf/materials.urdf.xacro" />

  <xacro:property name="JMlen" value=".1" />
  <xacro:property name="JMwidth" value=".4" />
  <xacro:property name="JMheight" value=".3" />


  <xacro:macro name="cuboid_inertial" params="mass len height width">
    <inertia ixx="${mass*(len*len+height*height)/12}" ixy="0" ixz="0" iyy="${mass*(width*width+len*len)/12}" iyz="0" izz="${(mass*(width*width+height*height)/12}"/>
  </xacro:macro>

  <xacro:macro name="cylinder_inertial" params="mass len radius">
    <inertia ixx="${mass*(len*len+3*radius*radius)/12}" ixy="0" ixz="0" iyy="${mass*(len*len+3*radius*radius)/12}" iyz="0" izz="${(mass*(radius*radius)/2}"/>
  </xacro:macro>
    
  <xacro:macro name="default_inertial" params="mass I_tensor">
<!--
      Inertia of solid cuboid - m*l*2/6
      Inertia of solid sphere - m*r*r*2/5 
-->
    <inertia ixx="${mass*I_tensor*1.0}" ixy="0.0" ixz="0.0" iyy="${mass*I_tensor*1.0}" iyz="0.0"
        izz="${mass*I_tensor*1.0}" />
  </xacro:macro>   

  <xacro:macro name="joint_module" params="parent prefix instance scale ">

    <xacro:jm_rec_link parent="${parent}" prefix="${prefix}" instance="1" scale="${scale}" />
    <xacro:jm_sphere_link parent="${prefix}_jm_link_${instance}" prefix="${prefix}" instance="1" scale="${scale}" />
<!--
    <xacro:jm_sphere_link parent="1_jm_link_1" prefix="${prefix}" instance="1" scale="${scale}" />
-->

  </xacro:macro>
  
    <xacro:macro name="jm_rec_link" params="parent prefix instance scale">
      <link name="${prefix}_jm_link_${instance}">
        <visual>
          <geometry>
            <box size="${JMlen*scale} ${JMwidth*scale} ${JMheight*scale}" />
          </geometry>
          <material name="Grey2">
          </material>
        </visual>
        <collision>
          <geometry>
            <box size="${JMlen*scale} ${JMwidth*scale} ${JMheight*scale}" />
          </geometry>
        </collision>
        <xacro:default_inertial mass="1" I_tensor="1"/>
      </link>
      <joint name="${prefix}_jm_joint_${instance}" type="continuous">
        <parent link="${parent}" />
        <child link="${prefix}_jm_link_${instance}" />
        <origin xyz="-0.3 -0.3 -0.3" rpy="0 0 0" />
      </joint>
      <gazebo reference = "${prefix}_jm_link_${instance}">
        <material>Gazebo/Grey</material>
      </gazebo>
    </xacro:macro>
    
    <xacro:macro name="jm_sphere_link" params="parent prefix instance scale">
      <link name="${prefix}_jm_link2_${instance}">
        <visual>
          <geometry>
            <sphere radius="${JMwidth/2*scale}"/>
          </geometry>
          <material name="Grey2">
          </material>
        </visual>
        <collision>
          <geometry>
            <sphere radius="${JMwidth/2*scale}"/>
          </geometry>
        </collision>
        <xacro:default_inertial mass="1" I_tensor="1"/>
      </link>
      <joint name="${prefix}_jm_joint2_${instance}" type="continuous">
        <parent link="${parent}" />
        <child link="${prefix}_jm_link2_${instance}" />
        <origin xyz="${(JMlen+JMwidth)/2} 0 0" rpy="0 0 0" />
      </joint>
      <gazebo reference = "${prefix}_jm_link2_${instance}">
        <material>Gazebo/Grey</material>
      </gazebo>
    </xacro:macro>
    
    <xacro:macro name="pcm_cube_link" params="parent prefix instance scale len">
      <link name="${prefix}_pcm_link_${instance}">
        <visual>
          <geometry>
            <box size="${len*scale} ${len*scale} ${len*scale}" />
          </geometry>
          <material name="Blue">
          </material>
        </visual>
        <collision>
          <geometry>
            <box size="${len*scale} ${len*scale} ${len*scale}" />
          </geometry>
        </collision>
        <xacro:default_inertial mass="1" I_tensor="1"/>
      </link>
      <joint name="${prefix}_pcm_joint_${instance}" type="fixed">
        <parent link="${parent}" />
        <child link="${prefix}_pcm_link_${instance}" />
<!--
        <origin xyz="1 0 0" rpy="0 0 0" />
-->
      </joint>

    </xacro:macro>
</robot>
